[credentials.web]
	client_id="755678439946-q15a8vlpnb6t4fgpgp3qrni5hlbn876h.apps.googleusercontent.com"
	project_id="smart-timetable-ai-488814"
	auth_uri="https://accounts.google.com/o/oauth2/auth"
	token_uri="https://oauth2.googleapis.com/token"
	auth_provider_x509_cert_url="https://www.googleapis.com/oauth2/v1/certs"
	client_secret="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"
	redirect_uris=["https://smart-timetable-ai.streamlit.app/"]